version: "3.8"

services:
 
  ###################################
  # Carpark: The Carpark microservice
  ###################################
  carpark:
    build:
      context: ./
      dockerfile: carpark.Dockerfile
    image: brendankhow/carpark:1.0
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://root:root@host.docker.internal:3306/carpark
      PYTHONUNBUFFERED: 1
    ports:
      - "5001:5001"

  ###################################
  # favourites: The favourites microservice
  ###################################
  favourites:
    build:
      context: ./
      dockerfile: favourites.Dockerfile
    image: brendankhow/favourites:1.0
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://root:root@host.docker.internal:3306/users_db
      PYTHONUNBUFFERED: 1
    ports:
      - "5003:5003"

  ###################################
  # geocode: The geocode microservice
  ###################################
  geocode:
    build:
      context: ./
      dockerfile: geocode.Dockerfile
    image: brendankhow/geocode:1.0
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://root:root@host.docker.internal:3306/location
      PYTHONUNBUFFERED: 1
    ports:
      - "3001:3001"

  ###################################
  # getcarpark: The getcarpark microservice
  ###################################
  getcarpark:
    build:
      context: ./
      dockerfile: getcarpark.Dockerfile
    image: brendankhow/getcarpark:1.0
    restart: always
    depends_on:
      - carpark
    environment:
      dbURL: mysql+mysqlconnector://root:root@host.docker.internal:3306/location
      PYTHONUNBUFFERED: 1
      carpark_URL: http://carpark:5001/consolidated
    ports:
      - "4002:4002"
      
  ###################################
  # notification: The notification microservice
  ###################################
  notification:
    build:
      context: ./
      dockerfile: notification.Dockerfile
    image: brendankhow/notification:1.0
    restart: always
    depends_on:
      - carpark
    environment:
      dbURL: mysql+mysqlconnector://root:root@host.docker.internal:3306/users_db
      PYTHONUNBUFFERED: 1
      carpark_URL: http://carpark:5001/consolidated
    ports:
      - "4004:4004"

  ###################################
  # users: The users microservice
  ###################################
  users:
    build:
      context: ./
      dockerfile: users.Dockerfile
    image: brendankhow/users:1.0
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://root:root@host.docker.internal:3306/users_db
      PYTHONUNBUFFERED: 1
    ports:
      - "5002:5002"