version: "3.8"

volumes:
  rabbitmq_data:

#followed lab for:
  #restart for all
  #PYTHONUNBUFFERED for all except rabbitmq

#TO DO:
# check if need to add ports? (add for those exposed to ui)
# check if need add dbURL
  #rmb set username to is213?instead of root? not sure how this wld work for profs
    #i think whovever has the DB needs to create the user (see lab 3)
services:
  carpark:
    build:
      context: ./
      dockerfile: carpark.Dockerfile
    image: liujh787/carpark:esd
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:8889/carpark
      PYTHONUNBUFFERED: 1

  getcarpark:
    build:
      context: ./
      dockerfile: getcarpark.Dockerfile
    image: liujh787/getcarpark:esd
    restart: always
    ports: "4002:4002"
    environment:
      PYTHONUNBUFFERED: 1

  users:
    build:
      context: ./
      dockerfile: users.Dockerfile
    image: liujh787/users:esd
    restart: always
    environment:
      PYTHONUNBUFFERED: 1

  favourites:
    build:
      context: ./
      dockerfile: favourites.Dockerfile
    image: liujh787/favourites:esd
    restart: always
    environment:
      PYTHONUNBUFFERED: 1

  geocode:
    build:
      context: ./
      dockerfile: geocode.Dockerfile
    image: liujh787/geocode:esd
    restart: always
    environment:
      PYTHONUNBUFFERED: 1

  sms_service:
    build:
      context: ./
      dockerfile: sms_service.Dockerfile
    image: liujh787/sms_service:esd
    restart: always
    environment:
      PYTHONUNBUFFERED: 1

#just copied and pasted frm lab. need to check values (esp. hostname, volumes)
#rmb to stop (and/or remove) the previous rabbitmq-mgmt container before running
    # docker compose up to avoid ports conflicts
  rabbitmq:
    image: rabbitmq:3-management
    hostname: esd-rabbit
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes: 
      - ./rabbitmq.config:/etc/rabbitmq/rabbitmq.config
      - ./rabbitmq_definitions.json:/etc/rabbitmq/rabbitmq_definitions.json
      - rabbitmq_data:/var/lib/rabbitmq
